<%@ Page Title="" Language="C#" MasterPageFile="~/ManagerPage.Master" AutoEventWireup="true" CodeBehind="ModifyCustomerInformation.aspx.cs" Inherits="NuiLunchBoxProject.WebForm16" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<fieldset style="width: 90%;float:left;margin-left:15px;margin-left:40px">
    <div class="gvclass">   
        <asp:GridView ID="CustomerInfo" runat="server" OnRowCommand="CustomerInfo_RowCommand" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="CustomerInfo_RowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" AllowPaging="True" CellPadding="4" ForeColor="#333333" ShowHeaderWhenEmpty ="True"
                GridLines="None" CssClass="table" Width="100%" ShowFooter="True" style="margin-top: 0px; margin-right: 0px;" HorizontalAlign="Center">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" HorizontalAlign="Center" />
           <Columns>  
               <asp:TemplateField>  
                   <ItemTemplate>
                    </ItemTemplate>
                   <EditItemTemplate>
                       
                   </EditItemTemplate>
                    <FooterTemplate>  
                    <asp:Button class="button button2" ID="btnInsert" runat="Server" Text="Insert" CommandName="UserInsert"/>
                    </FooterTemplate>  
            </asp:TemplateField>  
            <asp:TemplateField Headertext="ID">  
                <ItemTemplate>
                    <asp:Label ID="txtUserID" Text='<%#Eval("User_ID")%>' runat="server" />
                </ItemTemplate>
                <EditItemTemplate>  
                    <asp:TextBox ID="txtUserID" Text='<%#Eval("User_ID")%>' runat="server"></asp:TextBox>  
                </EditItemTemplate>  
                <FooterTemplate>  
                    <asp:TextBox ID="txtUserIDFooter" runat="server"></asp:TextBox>  
                </FooterTemplate>  
                <FooterStyle HorizontalAlign="Center" />
                <HeaderStyle HorizontalAlign="Center" />
                <ItemStyle HorizontalAlign="Center" />
            </asp:TemplateField>  
            <asp:TemplateField HeaderText="Password">  
                <ItemTemplate>
                    <asp:Label ID="txtUserPasswd" Text='<%#Eval("User_Passwd")%>' runat="server" />
                </ItemTemplate>
                <EditItemTemplate>  
                    <asp:TextBox ID="txtUserPasswd" Text='<%#Eval("User_Passwd")%>' runat="server"></asp:TextBox>  
                </EditItemTemplate>  
                <FooterTemplate>  
                    <asp:TextBox ID="txtUserPasswdFooter" runat="server"></asp:TextBox>  
                </FooterTemplate>   
             </asp:TemplateField>  
            <asp:TemplateField HeaderText="Name">  
                 <ItemTemplate>
                    <asp:Label ID="txtUserName" Text='<%#Eval("User_Name")%>' runat="server" />
                </ItemTemplate>
                <EditItemTemplate>  
                    <asp:TextBox ID="txtUserName" Text='<%#Eval("User_Name")%>' runat="server"></asp:TextBox>  
                </EditItemTemplate>  
                <FooterTemplate>  
                    <asp:TextBox ID="txtUserNameFooter" runat="server"></asp:TextBox>  
                </FooterTemplate>  
            </asp:TemplateField>  
            <asp:TemplateField HeaderText="Email">  
                <ItemTemplate>
                    <asp:Label ID="txtUserEmail" Text='<%#Eval("User_Email")%>' runat="server" />
                </ItemTemplate>
                <EditItemTemplate>  
                    <asp:TextBox ID="txtUserEmail" Text='<%#Eval("User_Email")%>' runat="server"></asp:TextBox>  
                </EditItemTemplate>  
                <FooterTemplate>  
                    <asp:TextBox ID="txtUserEmailFooter" runat="server"></asp:TextBox>  
                </FooterTemplate> 
               </asp:TemplateField>  
               <asp:TemplateField HeaderText="Mobile">  
                <ItemTemplate>
                    <asp:Label ID="txtUserMobile" Text='<%#Eval("User_Mobile")%>' runat="server" />
                </ItemTemplate>
                <EditItemTemplate>  
                    <asp:TextBox ID="txtUserMobile" Text='<%#Eval("User_Mobile")%>' runat="server"></asp:TextBox>  
                </EditItemTemplate>  
                <FooterTemplate>  
                    <asp:TextBox ID="txtUserMobileFooter" runat="server"></asp:TextBox>  
                </FooterTemplate> 
               </asp:TemplateField>  
         </Columns>  
    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="Black" HorizontalAlign="Center" />  
    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" HorizontalAlign="Center" />  
    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />  
    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" HorizontalAlign="Center" />  
    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" HorizontalAlign="Center" />  
    <SortedAscendingCellStyle BackColor="#E9E7E2" />  
    <SortedAscendingHeaderStyle BackColor="#506C8C" />  
    <SortedDescendingCellStyle BackColor="#FFFDF8" />  
    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
      </asp:GridView>
    </div>
    <br />
    <asp:Label ID="lblSuccessMessage" Text="" runat="server" ForeColor="Green" />
    <br />
    <asp:Label ID="lblErrorMessage" Text="" runat="server" ForeColor="Red" />
    </fieldset>
</asp:Content>
